version: '3'

services:
  api:
    build: 
      dockerfile: Dockerfile.dev
      context: ./api
    command: ["flask", "run", "--host=0.0.0.0"]
    volumes:
      - ./api:/backend
    environment:
      - FLASK_ENV=development
      - FLASK_APP=app.py
  
  nginx:
     restart: always
     build: 
       dockerfile : Dockerfile.dev
       context : ./nginx
     ports:
       - '3050:80'

  client:
    build: 
       dockerfile: Dockerfile.dev
       context: ./client
    command: ["npm", "start"]
    volumes:
      - ./client:/frontend
      - node_modules:/frontend/node_modules
    environment:
      - NODE_ENV=development
    ports:
      - '3000:3000'
  

volumes:
  node_modules: