version: '3'

services:
  api:
    build: 
      dockerfile: Dockerfile.dev
      context: .
    volumes:
      - .:/backend
    environment:
      - FLASK_ENV=development
      - FLASK_APP=run.py
    ports:
      - '80:5000'
  

