export let initialstate = {
    "pi":"",
   "Medication item":"",
   "Name":"",
   "Form":"",
   "strength":0,
   "strengthUnit":"",
   "numerator":0,
   "numeratorUnit":"",
   "substanceName":"",
   "ingredientForm":"",
   "category":"",
   "ingredientstrength":0,
   "strengthUnit":"",
   "medicationDescription":"",
   "ingredient-amount":0,
   "ingredient-amountUnit":"",
   "roleStatus":"",
   "role":"",
   "description":"",
   "route":"",
   "dosageInstructions":"",
   "doseAmount":0,
   "doseAmountLower":0,
   "doseAmountUpper":0,
   "doseUnit":"",
   "frequency":0,
   "frequencyUnit":"",
   "frequencyLower":0,
   "frequencyLowerUnit":"",
   "frequencyUpper":0,
   "frequencyUpperUnit":"",
   "interval":"",
   "st":"",
   "nte":"",
   "nte2":"",
   "timeCritical":0,
   "asRequired":0,
   "requiredcriterion":"",
   "iar":0,
   "iarUnit":"",
   "iar1":"",
   "administration":"",
   "directionDuration":"",
   "directionDuration2":"",
   "repetitionInterval":"",
   "specificDate":new Date(),
   "specificTime":new Date(),
   "specificDayofweek":0,
   "specificdayofmonth":0,
   "eventName":"",
   "eventStartInterval":"",
   "maximumAmount":0,
   "maximumAmountDoseUnit":"",
   "allowedPeriod":"",
   "overrideReason":"",
   "additionalInstructions":"",
   "reason":"",
   "status":"",
   "dateDiscontinued":new Date(),
   "timeDiscontinued":"00:00:00",
   "dateWritten":new Date(),
   "timeWritten":"00:00:00",
   "nora":0,
   "validityPeriod":new Date(),
   "validityPeriodTime":"00:00:00/",
   "dispenseInstructions":"",
   "amountDescription":"",
   "amountindispense":0,
   "dispenseUnits":"",
   "dos":"",
   "comment":"",
   "identifier":""
}